import { Book } from './context/CartContext';

export const allBooks: Book[] = [
  {
    id: 101,
    title: "İnsanlığımı Yitirirken",
    author: "Osamu Dazai",
    publisher: "Can Yayınları",
    price: "85.00",
    oldPrice: "110.00",
    rating: 4.8,
    reviews: 450,
    image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&q=100&w=1200",
    badge: "Editörün Seçimi",
    sellers: 4,
    isFastShipping: true,
    category: "Roman",
    description: "İkinci Dünya Savaşı sonrası Japon edebiyatının en önemli eserlerinden biri olan İnsanlığımı Yitirirken, toplumun beklentilerine uyum sağlayamayan bir adamın trajik hikayesini anlatıyor."
  },
  {
    id: 102,
    title: "1984",
    author: "George Orwell",
    publisher: "Can Yayınları",
    price: "95.00",
    oldPrice: "130.00",
    rating: 4.9,
    reviews: 8900,
    image: "https://images.unsplash.com/photo-1541963463532-d68292c34b19?auto=format&fit=crop&q=100&w=1200",
    badge: "Klasik",
    sellers: 22,
    isFastShipping: true,
    category: "Edebiyat",
    description: "George Orwell'in kült eseri 1984, totaliter bir gelecekte bireyin özgürlük mücadelesini ve gözetim toplumunun karanlık yüzünü gözler önüne seriyor."
  },
  {
    id: 103,
    title: "Simyacı",
    author: "Paulo Coelho",
    publisher: "Can Yayınları",
    price: "115.00",
    oldPrice: "150.00",
    rating: 4.7,
    reviews: 12000,
    image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&q=100&w=1200",
    badge: "Dünya Çapında",
    sellers: 18,
    isFastShipping: false,
    category: "Roman",
    description: "Santiago'nun hazinesini aramak için çıktığı yolculuk, aslında kendi kişisel menkıbesini bulma yolculuğudur."
  },
  {
    id: 104,
    title: "Kürk Mantolu Madonna",
    author: "Sabahattin Ali",
    publisher: "Yapı Kredi Yayınları",
    price: "75.00",
    oldPrice: "95.00",
    rating: 4.9,
    reviews: 15000,
    image: "https://images.unsplash.com/photo-1543004218-ee141104638e?auto=format&fit=crop&q=100&w=1200",
    badge: "Yerli Klasik",
    sellers: 30,
    isFastShipping: true,
    category: "Roman",
    description: "Raif Efendi'nin Maria Puder'e olan derin ve sessiz aşkı, Türk edebiyatının en unutulmaz hikayelerinden biridir."
  },
  {
    id: 201,
    title: "Yarının Hikayesi",
    author: "Elif Şafak",
    publisher: "Doğan Kitap",
    price: "185.00",
    oldPrice: "240.00",
    rating: 4.5,
    reviews: 120,
    image: "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?auto=format&fit=crop&q=100&w=1200",
    badge: "Yeni Çıkan",
    sellers: 3,
    isFastShipping: true,
    category: "Roman",
    description: "Elif Şafak'ın son romanı, geçmişin gölgeleriyle geleceğin umutları arasında gidip gelen büyüleyici bir anlatı sunuyor."
  },
  {
    id: 202,
    title: "Zamanın Kısa Tarihi",
    author: "Stephen Hawking",
    publisher: "Alfa Yayınları",
    price: "155.00",
    oldPrice: "200.00",
    rating: 4.9,
    reviews: 2100,
    image: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&q=100&w=1200",
    badge: "Bilim",
    sellers: 12,
    isFastShipping: true,
    category: "Bilim",
    description: "Stephen Hawking, evrenin başlangıcından sonuna kadar olan süreci herkesin anlayabileceği bir dille anlatıyor."
  },
  {
    id: 203,
    title: "Düşün ve Zengin Ol",
    author: "Napoleon Hill",
    publisher: "Pegasus Yayınları",
    price: "125.00",
    oldPrice: "170.00",
    rating: 4.6,
    reviews: 5400,
    image: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&q=100&w=1200",
    badge: "Kişisel Gelişim",
    sellers: 8,
    isFastShipping: false,
    category: "Kişisel Gelişim",
    description: "Başarının sırlarını keşfetmek isteyenler için bir başucu kitabı."
  }
];
